apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: ethereum-analytics
  namespace: ethereum
spec:
  configuration:
    clusters:
      - name: analytics
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      # Server-level: total memory cap (90% of 16Gi = ~14.4Gi)
      max_server_memory_usage_to_ram_ratio: "0.9"
    users:
      etherwurst/password: "etherwurst-ch-2026"
      etherwurst/networks/ip:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
      etherwurst/profile: analytics
      etherwurst/quota: default
      # Read-only user for dashboards and AI agents
      reader/password: "reader-ch-2026"
      reader/networks/ip:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
      reader/profile: readonly
      reader/quota: default
    profiles:
      # Analytics profile: full power for ETL and investigations
      analytics/max_memory_usage: "5000000000"
      analytics/max_threads: "4"
      analytics/max_execution_time: "300"
      analytics/use_uncompressed_cache: "1"
      analytics/max_bytes_before_external_group_by: "2500000000"
      analytics/max_bytes_before_external_sort: "2500000000"
      analytics/join_algorithm: "auto"
      # Read-only profile: safe for dashboards/agents
      readonly/readonly: "1"
      readonly/max_memory_usage: "4000000000"
      readonly/max_threads: "2"
      readonly/max_execution_time: "60"
  defaults:
    templates:
      podTemplate: clickhouse-pod
      dataVolumeClaimTemplate: data-volume
      serviceTemplate: clickhouse-svc
  templates:
    serviceTemplates:
      - name: clickhouse-svc
        generateName: clickhouse-{chi}
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
    podTemplates:
      - name: clickhouse-pod
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.12
              resources:
                requests:
                  cpu: "2"
                  memory: "8Gi"
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: managed-csi-premium
          resources:
            requests:
              storage: 500Gi
