apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lighthouse
  namespace: ethereum
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      chart: lighthouse
      sourceRef:
        kind: HelmRepository
        name: ethereum-helm-charts
        namespace: flux-system
  values:
    fullnameOverride: lighthouse
    image:
      repository: sigp/lighthouse
      tag: v8.1.1
    mode: beacon
    jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a
    checkpointSync:
      enabled: true
      url: https://beaconstate.ethstaker.cc
    extraArgs:
      - --network=mainnet
      - --execution-endpoint=http://erigon:8551
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
    persistence:
      enabled: true
      storageClassName: managed-csi-premium
      size: 50Gi
      accessModes:
        - ReadWriteOnce
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
    tolerations:
      - key: ethereum-node
        operator: Equal
        value: "true"
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload-type
                  operator: In
                  values: ["ethereum"]
