apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lighthouse
  namespace: ethereum
spec:
  interval: 1h
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      chart: lighthouse
      sourceRef:
        kind: HelmRepository
        name: ethereum-helm-charts
        namespace: flux-system
  values:
    fullnameOverride: lighthouse
    image:
      repository: sigp/lighthouse
      tag: v8.1.1
    persistence:
      enabled: true
      storageClassName: managed-csi-premium
      size: 50Gi
      accessModes:
        - ReadWriteOnce
    resources:
      requests:
        cpu: "500m"
        memory: "4Gi"
    extraArgs:
      - --execution-endpoint=http://erigon:8551
    checkpointSync:
      enabled: true
      url: "https://beaconstate.ethstaker.cc"
    p2pNodePort:
      enabled: false
    tolerations:
      - key: ethereum-node
        operator: Equal
        value: "true"
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload-type
                  operator: In
                  values: ["ethereum"]
