apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: ethereum
spec:
  interval: 1h
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: "0.26.0"
      sourceRef:
        kind: HelmRepository
        name: altinity
        namespace: flux-system
