apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: flux-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
  values:
    webUI:
      enabled: true
